version: "3.9"

services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "80:80"

  api-nginx:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app

  api-go:
    build:
      context: api/docker
      dockerfile: development/go/Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    environment:
      TZ: Europe/Moscow
      APP_NAME: PrimeDividend
      APP_ENV: development
      SITE_ORIGIN: http://localhost
      DB_HOST: api-postgres
      DB_PORT: 5432
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD_FILE: /run/secrets/api_db_password
      GOOSE_DRIVER: postgres
      GOOSE_DIR_MIGRATIONS: ./database/migrations
      REDIS_HOST: api-redis
      REDIS_PORT: 6379
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: app
      MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
      MAILER_FROM_EMAIL: mail@app.test
      MAILER_FROM_NAME: PrimeDividend
      JWT_ACCESS_SECRET_KEY: secret
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_SECRET_KEY: secret
      JWT_REFRESH_EXPIRES_IN: 1440h
      VK_OAUTH_CLIENT_ID: ${VK_OAUTH_CLIENT_ID}
      VK_OAUTH_CLIENT_SECRET: ${VK_OAUTH_CLIENT_SECRET}
      VK_OAUTH_SCOPES: ${VK_OAUTH_SCOPES}
      YANDEX_OAUTH_CLIENT_ID: ${YANDEX_OAUTH_CLIENT_ID}
      YANDEX_OAUTH_CLIENT_SECRET: ${YANDEX_OAUTH_CLIENT_SECRET}
      YANDEX_OAUTH_SCOPES: ${YANDEX_OAUTH_SCOPES}
      OK_OAUTH_CLIENT_ID: ${OK_OAUTH_CLIENT_ID}
      OK_OAUTH_CLIENT_KEY: ${OK_OAUTH_CLIENT_KEY}
      OK_OAUTH_CLIENT_SECRET: ${OK_OAUTH_CLIENT_SECRET}
      OK_OAUTH_SCOPES: ${OK_OAUTH_SCOPES}
      TINKOFF_AUTH_TOKEN: ${TINKOFF_AUTH_TOKEN}
    secrets:
      - api_db_password
      - api_mailer_password
    volumes:
      - ./api:/app
      - ./specs:/app/specs:ro
    command: sh -c "until [ -f .done ] ; do sleep 1 ; done && air"

  front-nginx:
    build:
      context: front/docker/development/nginx

  front-node:
    build:
      context: front/docker/development/node
    volumes:
      - ./front:/app
    command: sh -c "until [ -f .done ] ; do sleep 1 ; done && yarn dev"
    tty: true

  api-postgres:
    image: postgres:13.3-alpine
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/api_db_password
    secrets:
      - api_db_password
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  api-redis:
    image: redis:6-alpine
    ports:
      - "63791:6379"
    environment:
      TZ: Europe/Moscow
    restart: on-failure
    volumes:
      - api-redis:/data

  api-swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /specs/swagger.yml
    volumes:
      - ./specs/openapi:/specs

  api-swagger-editor:
    image: swaggerapi/swagger-editor
    environment:
      SWAGGER_FILE: /specs/swagger.yml
    volumes:
      - ./specs/openapi:/specs

  mailer:
    image: mailhog/mailhog

secrets:
  api_db_password:
    file: ./docker/development/secrets/api_db_password
  api_mailer_password:
    file: ./docker/development/secrets/api_mailer_password

volumes:
  api-postgres:
  api-redis:
