package: openapi

#additional-imports:
#  - package: primedividend/api/internal/infrastructure/server/openapi/openapi_types
#    alias: "."

generate:
  chi-server: true
  models: false
  strict-server: true
  embedded-spec: true

output: "../../internal/infrastructure/server/openapi/openapi.gen.go"
