// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthConfirm defines model for authConfirm.
type AuthConfirm struct {
	Token openapi_types.UUID `json:"token" validate:"required"`
}

// AuthToken defines model for authToken.
type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiresAt   time.Time `json:"expiresAt"`
}

// AuthUser defines model for authUser.
type AuthUser struct {
	Email    string `json:"email" validate:"required,email"`
	Name     string `json:"name"`
	Password string `json:"password" validate:"required,min=6"`
}

// Detail defines model for detail.
type Detail struct {
	// Поле в котором произошла ошибка
	Field string `json:"field"`

	// Описание ошибки
	Message string `json:"message"`
}

// Error defines model for error.
type Error struct {
	// Объект ошибки
	Error ErrorMessage `json:"error"`
}

// Объект ошибки
type ErrorMessage struct {
	// В каком поле произошла ошибка
	Details []Detail `json:"details"`

	// Описание ошибки
	Message string `json:"message"`
}

// Instrument defines model for instrument.
type Instrument struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Title       string             `json:"title"`
}

// Instruments defines model for instruments.
type Instruments = []Instrument

// LoginUser defines model for loginUser.
type LoginUser struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6"`
}

// Portfolio defines model for portfolio.
type Portfolio struct {
	Active     bool               `json:"active"`
	CreatedAt  time.Time          `json:"createdAt"`
	CurrencyId openapi_types.UUID `json:"currencyId"`
	Id         openapi_types.UUID `json:"id"`
	Title      string             `json:"title"`
	UpdatedAt  *time.Time         `json:"updatedAt,omitempty"`
	UserId     openapi_types.UUID `json:"userId"`
}

// PortfolioAdd defines model for portfolioAdd.
type PortfolioAdd struct {
	CurrencyId openapi_types.UUID `json:"currencyId" validate:"required,uuid"`
	Title      string             `json:"title" validate:"required"`
}

// PortfolioUpdate defines model for portfolioUpdate.
type PortfolioUpdate struct {
	Active     *bool               `json:"active,omitempty"`
	CurrencyId *openapi_types.UUID `json:"currencyId,omitempty" validate:"omitempty,required,uuid"`
	Title      *string             `json:"title,omitempty" validate:"omitempty,required"`
}

// Code defines model for code.
type Code = string

// Network defines model for network.
type Network = string

// PortfolioId defines model for portfolioId.
type PortfolioId = openapi_types.UUID

// State defines model for state.
type State = string

// N400 defines model for 400.
type N400 = Error

// N403 defines model for 403.
type N403 = Error

// N500 defines model for 500.
type N500 = Error

// JoinEmailJSONBody defines parameters for JoinEmail.
type JoinEmailJSONBody = AuthUser

// ConfirmEmailJSONBody defines parameters for ConfirmEmail.
type ConfirmEmailJSONBody = AuthConfirm

// LoginEmailJSONBody defines parameters for LoginEmail.
type LoginEmailJSONBody = LoginUser

// ConfirmNetworkParams defines parameters for ConfirmNetwork.
type ConfirmNetworkParams struct {
	Code  Code  `form:"code" json:"code"`
	State State `form:"state" json:"state"`
}

// CreatePortfolioJSONBody defines parameters for CreatePortfolio.
type CreatePortfolioJSONBody = PortfolioAdd

// UpdatePortfolioJSONBody defines parameters for UpdatePortfolio.
type UpdatePortfolioJSONBody = PortfolioUpdate

// JoinEmailJSONRequestBody defines body for JoinEmail for application/json ContentType.
type JoinEmailJSONRequestBody = JoinEmailJSONBody

// ConfirmEmailJSONRequestBody defines body for ConfirmEmail for application/json ContentType.
type ConfirmEmailJSONRequestBody = ConfirmEmailJSONBody

// LoginEmailJSONRequestBody defines body for LoginEmail for application/json ContentType.
type LoginEmailJSONRequestBody = LoginEmailJSONBody

// CreatePortfolioJSONRequestBody defines body for CreatePortfolio for application/json ContentType.
type CreatePortfolioJSONRequestBody = CreatePortfolioJSONBody

// UpdatePortfolioJSONRequestBody defines body for UpdatePortfolio for application/json ContentType.
type UpdatePortfolioJSONRequestBody = UpdatePortfolioJSONBody
