##### Аутентификация и авторизация #####

#### Создание пользователя
POST {{host}}/auth/email
Content-type: application/json

{
  "email": "test@mail.ru",
  "password": "123456"
}

#### Подтверждение почты
POST {{host}}/auth/email/confirm
Content-type: application/json

{
  "token": "49e84101-8c73-42fc-accf-316e72e70a95"
}

#### Аутентификация по Email
POST {{host}}/auth/email/login
Content-type: application/json

{
  "email": "test@mail.ru",
  "password": "123456"
}

#### Выход из аккаунта
POST {{host}}/auth/logout
Cookie: refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNDkwYTAyN2EtN2Y1NC00YzI0LTkyZGUtMjdhYzkyNjhiZDcxIiwiaXNzIjoiUHJpbWVEaXZpZGVuZCIsImV4cCI6MTY2OTU4MjEwNCwiaWF0IjoxNjY0Mzk4MTA0fQ.tTPyBr_xO0W9SDLzRyZvTFCmQQ0WcijNLg1XGxtMMgI
