#### Портфель по ИД
GET {{host}}/portfolio/{{portfolioId}}
Content-type: application/json
Accept: application/xml

#### Список портфелей
GET {{host}}/portfolio?limit=5
Content-type: application/json

#### Создать новый портфель
POST {{host}}/portfolio
Content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Всепогодный",
  "currencyId": "e6dffe5f-af39-44c4-a9f2-4938cceb7f7c"
}

#### Редактировать портфель по ИД
PATCH {{host}}/portfolio/{{portfolioId}}
Content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Рискованный"
}

#### Удалить портфель
DELETE {{host}}/portfolio/{{portfolioId}}
Content-type: application/json
Authorization: Bearer {{accessToken}}
