//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Instruments = newInstrumentsTable("public", "instruments", "")

type instrumentsTable struct {
	postgres.Table

	//Columns
	ID          postgres.ColumnString
	Title       postgres.ColumnString
	Description postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type InstrumentsTable struct {
	instrumentsTable

	EXCLUDED instrumentsTable
}

// AS creates new InstrumentsTable with assigned alias
func (a InstrumentsTable) AS(alias string) *InstrumentsTable {
	return newInstrumentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InstrumentsTable with assigned schema name
func (a InstrumentsTable) FromSchema(schemaName string) *InstrumentsTable {
	return newInstrumentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new InstrumentsTable with assigned table prefix
func (a InstrumentsTable) WithPrefix(prefix string) *InstrumentsTable {
	return newInstrumentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new InstrumentsTable with assigned table suffix
func (a InstrumentsTable) WithSuffix(suffix string) *InstrumentsTable {
	return newInstrumentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newInstrumentsTable(schemaName, tableName, alias string) *InstrumentsTable {
	return &InstrumentsTable{
		instrumentsTable: newInstrumentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newInstrumentsTableImpl("", "excluded", ""),
	}
}

func newInstrumentsTableImpl(schemaName, tableName, alias string) instrumentsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		TitleColumn       = postgres.StringColumn("title")
		DescriptionColumn = postgres.StringColumn("description")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, TitleColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{TitleColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return instrumentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Title:       TitleColumn,
		Description: DescriptionColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
