// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Аутентификация по Email
	// (POST /auth/email)
	AuthEmail(w http.ResponseWriter, r *http.Request)
	// Авторизация по Email
	// (POST /auth/email/confirm)
	AuthEmailConfirm(w http.ResponseWriter, r *http.Request)
	// Аутентификация в соц. сетях
	// (GET /auth/{network})
	AuthNetwork(w http.ResponseWriter, r *http.Request, network Network)
	// Авторизация в соц. сетях
	// (GET /auth/{network}/callback)
	AuthNetworkCallback(w http.ResponseWriter, r *http.Request, network Network)

	// (GET /instrument)
	GetInstruments(w http.ResponseWriter, r *http.Request)
	// Создание портфеля
	// (POST /portfolio)
	CreatePortfolio(w http.ResponseWriter, r *http.Request)
	// Получение портфеля по ID
	// (GET /portfolio/{portfolioId})
	GetPortfolioById(w http.ResponseWriter, r *http.Request, portfolioId PortfolioId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// AuthEmail operation middleware
func (siw *ServerInterfaceWrapper) AuthEmail(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthEmail(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AuthEmailConfirm operation middleware
func (siw *ServerInterfaceWrapper) AuthEmailConfirm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthEmailConfirm(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AuthNetwork operation middleware
func (siw *ServerInterfaceWrapper) AuthNetwork(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "network" -------------
	var network Network

	err = runtime.BindStyledParameter("simple", false, "network", chi.URLParam(r, "network"), &network)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "network", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthNetwork(w, r, network)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AuthNetworkCallback operation middleware
func (siw *ServerInterfaceWrapper) AuthNetworkCallback(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "network" -------------
	var network Network

	err = runtime.BindStyledParameter("simple", false, "network", chi.URLParam(r, "network"), &network)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "network", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthNetworkCallback(w, r, network)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetInstruments operation middleware
func (siw *ServerInterfaceWrapper) GetInstruments(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstruments(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreatePortfolio operation middleware
func (siw *ServerInterfaceWrapper) CreatePortfolio(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePortfolio(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPortfolioById operation middleware
func (siw *ServerInterfaceWrapper) GetPortfolioById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "portfolioId" -------------
	var portfolioId PortfolioId

	err = runtime.BindStyledParameter("simple", false, "portfolioId", chi.URLParam(r, "portfolioId"), &portfolioId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "portfolioId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPortfolioById(w, r, portfolioId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/email", wrapper.AuthEmail)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/email/confirm", wrapper.AuthEmailConfirm)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/{network}", wrapper.AuthNetwork)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/{network}/callback", wrapper.AuthNetworkCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/instrument", wrapper.GetInstruments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/portfolio", wrapper.CreatePortfolio)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/portfolio/{portfolioId}", wrapper.GetPortfolioById)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYS2/cthb+KwLvXcqWHfvexQAFGjtp6z5So0nQheEFLdFjxZKokJRjwxggdh59JKiD",
	"rLooGmTT9cSxm+k4Hv+Fw39UkJRmpBE9kBO7QFfzIHnO4Xe+c/iRu8incUoTkgiOWrsoxQzHRBCmfyVE",
	"PKBsU30NE9RCKRYbyEUJjglqDUddxMj9LGQkQC3BMuIi7m+QGKtlYidVU7lgYdJGnY6LUsrEOo1CuhSc",
	"Y7c8Y5LtdcpiLFALZVmoZo776qjFPKUJJ3o312Zm1EdAuM/CVIRUuf72K9Rx0bWZ2frQIiNYkMCMz9fH",
	"b1FnkSaCJEJNmbOZ+IZukcBZJizGCuJoR82cN3H4+drWLsJpGoU+Vou8e1yt3C3t87+MrKMW+o83SpVn",
	"RrlHGKPM7LXqeQEHznfkfka4ju5//4TP24RtEebczMeLXGnwcSY2FmmyHrJY84zRlDARmswIukmSOl1c",
	"tD1FcRpO+TQgbZJMkW3B8JTAbb1qC0dhgIVaMCRJnvWCMiu56dUhO+jaPeJrSFREdzlh9XBIjMOowjCy",
	"jeM0Ip/mn9Msq/Ht4sG6xo8uCsz5A8qCy8DAjcPkk//XkTDeSr5soJjc1hAJsNC0SLIowmsRMcVYnl9l",
	"AvwOb+TPcAx9ue/AQP4IPXgDfegp/1XLROAw4hYTLx3oQxf6MID3DpzBAE7g2IEz+RAG0IN32uwJdMv2",
	"u8hFoSAxr28hJpzjNrHGegY9uQddOIWeclGNd6ytuEhg1ibCYuhVEeOhCn0g92Ggg33fIOp6oyznrgje",
	"lrL8D8wY1u3l8jbKBRaZJTVf3LmzrHcIR+fYSLJ4jbCJYP0Gx3JPQeTAWzhqlNkx42MY5dEOXboTUBsv",
	"DcVibkU3TLhgWZw3zSqlfHNAXBeVXqHKcUqEMbFBWgFhtz4eBg1ONheJUETEaiBLg4vFNAaF8afNV6N1",
	"S9stu5kMmsZpWJGTTpUS0BZSDzXBpWShEco2YEa+bNseBnk3NT25FmrGGEn8naUG/j+g8Ws7nfPp8UHn",
	"qYsyTtjVRjx+Zuf0yx27ZdystcyJn7FQ7NxWXDJQLxDMCLueiQ31a03/+qwI/8vv76BcnShLZnS0nw0h",
	"UhMV2RaEJTi6QX3bEfUazuBYPoWefAw91aT09wPn9gPcbmuLGYtyg7zledz8Px1Sj6fED9dzAWZqZp3W",
	"XVxfXnLgCE7kgemPPTiBAfwJx6qFywNnmYUxuRFuhQFJRpXbQuP/bxHGjcXZ6ZnpWeWQpiTBaYhaaG56",
	"ZnpGKwOxobfpKW3kDWVQSrkuLkVlHa9iA1LY3sw1BTNKc4EGO5cmM4f6bIwfufIYk/az55kbzvPUpJH8",
	"njxXTRrJ5slz1STNwiyOMdtRxHghH8l9lSS5XyOHkjJOAZwpjhUtRtGqslLC3vNLgnlyDgppfXWpKDw0",
	"ysZMk2x8HMJwmOsrJRguhO1ufnHtKMe5OKnDemt4uy3fiVfsoY6meMWtuLM6hspcE47OGY5eCe8OHbkH",
	"A/l0Wn0ey315IJ80gcnzcRStYX+zCV6Lxdx/F252NjVHrCoTrSB9TsRSSRfZa6ZxudrvZ80EFjciYewY",
	"rV3n4aXatQM9OFVKXT6Uj+C9IZd8dmG0C9BKSBnoqtLO2ubMS8zycOLVdLlx+dao08036XTzF+dmrmh0",
	"5ZS1zMqqKpASdV/DAN7B0ehSd6Z4LPflYzhWuqHE1xHSY8h7u6U3t84kBg9zsLCjldnFarz8sler86uv",
	"gNH+G/Ff0IB+TFPRzwHykfzBqDVLbsx5tXTjvBxpIrCtAt1qeF9TH0eOGa8ozZbnRWpsg3LhKYWnoM7t",
	"1yTshBPDdaBr64uuaglH9jWjV1zdHDtuzeGvcAqHxd1fPhwtyLTWqy94CV04kb/Iff0GkE8ubgS2Ba9g",
	"oK2r4H/SwfWK95iefmI4hAH0S+/NjCqdbHX+h87dqXx2biN0TRKhDyfQlXtyrwqJfhXJHVWuuNbLRE+d",
	"N9B35NPCr3ziwBvtrwtvR6ZizDbJOWYO5QG8k88duWcIV8VCP0fV0HCgN3QKA/ir5FT9HDlmpB1yYQfr",
	"VYXdzzVg5VyXE1iqxbqhF9BX4cGhfDbRCOZcgbDa+TsAAP//v9buhccYAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
