// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Аутентификация по Email
	// (POST /auth/email)
	AuthEmail(w http.ResponseWriter, r *http.Request)
	// Авторизация по Email
	// (POST /auth/email/confirm)
	AuthEmailConfirm(w http.ResponseWriter, r *http.Request)
	// Аутентификация в соц. сетях
	// (GET /auth/{network})
	AuthNetwork(w http.ResponseWriter, r *http.Request, network Network)
	// Авторизация в соц. сетях
	// (GET /auth/{network}/callback)
	AuthNetworkCallback(w http.ResponseWriter, r *http.Request, network Network)

	// (GET /instrument)
	GetInstruments(w http.ResponseWriter, r *http.Request)
	// Создание портфеля
	// (POST /portfolio)
	CreatePortfolio(w http.ResponseWriter, r *http.Request)
	// Получение портфеля по ID
	// (GET /portfolio/{portfolioId})
	GetPortfolioById(w http.ResponseWriter, r *http.Request, portfolioId PortfolioId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// AuthEmail operation middleware
func (siw *ServerInterfaceWrapper) AuthEmail(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthEmail(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AuthEmailConfirm operation middleware
func (siw *ServerInterfaceWrapper) AuthEmailConfirm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthEmailConfirm(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AuthNetwork operation middleware
func (siw *ServerInterfaceWrapper) AuthNetwork(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "network" -------------
	var network Network

	err = runtime.BindStyledParameter("simple", false, "network", chi.URLParam(r, "network"), &network)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "network", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthNetwork(w, r, network)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AuthNetworkCallback operation middleware
func (siw *ServerInterfaceWrapper) AuthNetworkCallback(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "network" -------------
	var network Network

	err = runtime.BindStyledParameter("simple", false, "network", chi.URLParam(r, "network"), &network)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "network", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthNetworkCallback(w, r, network)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetInstruments operation middleware
func (siw *ServerInterfaceWrapper) GetInstruments(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstruments(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreatePortfolio operation middleware
func (siw *ServerInterfaceWrapper) CreatePortfolio(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePortfolio(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPortfolioById operation middleware
func (siw *ServerInterfaceWrapper) GetPortfolioById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "portfolioId" -------------
	var portfolioId PortfolioId

	err = runtime.BindStyledParameter("simple", false, "portfolioId", chi.URLParam(r, "portfolioId"), &portfolioId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "portfolioId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPortfolioById(w, r, portfolioId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/email", wrapper.AuthEmail)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/email/confirm", wrapper.AuthEmailConfirm)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/{network}", wrapper.AuthNetwork)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/{network}/callback", wrapper.AuthNetworkCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/instrument", wrapper.GetInstruments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/portfolio", wrapper.CreatePortfolio)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/portfolio/{portfolioId}", wrapper.GetPortfolioById)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYy27cNhd+FYH/v5QtO3a7GKBAYydt3UtqNAm6MLygJXqsWBIVknJsGAPEzqWXBHWQ",
	"VRdFg2y6njh2Mx3H41c4fKOCpDTSjOipnMQFupoLD885/M7tI3eRT+OUJiQRHLV2UYoZjokgTP9KiLhH",
	"2ab6GiaohVIsNpCLEhwT1BquuoiRu1nISIBagmXERdzfIDFW28ROqkS5YGHSRp2Oi1LKxDqNQroUnKO3",
	"KjFJ9zplMRaohbIsVJLjtjpqM09pwok+zZWZGfUREO6zMBUhVaa//Qp1XHRlZra+tMgIFiQw6/P19RvU",
	"WaSJIIlQInM2Fd/QLRI4y4TFWEEc7SjJeeOHn+9t7SKcplHoY7XJu8PVzt3KOf/PyDpqof95Zag8s8o9",
	"whhl5qyjlhdw4HxH7maEa+8++jds3iRsizDner5exEqDjzOxsUiT9ZDFOs8YTQkToYmMoJsk+eeQumh7",
	"iuI0nPJpQNokmSLbguEpgdtayxaOwgALtWGYNHkWFCm0kptaHaqma3eIryFSHt7mhNXdIzEOoxH3yDaO",
	"04h8mn9Os+wDOOsaO7pIMOf3KAvqJfQOauMw+eTjOhLGWsWWDRQT6xoiARY6TZIsivBaRExxVuVHMwN+",
	"h1fyZziGvtx3YCB/hB68gj70lP1RzUTgMOIWFc8d6EMX+jCAtw6cwQBO4NiBM3kfBtCDN1rtCXSr+rvI",
	"RaEgMa8fISac4zax+noGPbkHXTiFnjIx6u9Ym3GRwKxNhEXRi8LHQ+X6QO7DQDv7toHX9cZZjV3hvC1k",
	"+R+YMazbzYc7KBdYZJbQfHHr1rI+IRydoyPJ4jXCJoL1GxzLPQWRA6/hqFFkx5SPYZR7OzTpTkBtvDRU",
	"FnMrumHCBcvivImO527lRLt1/MKgwdhykQhFROzDs+qk2axlRxuxi3wzua6qQ2dpkH+ffBx9gmGtTOr/",
	"FQgs6Tac3nV8SreqMCj3pkQYExsWjSCzAVPash176OTt1HTLmqsZYyTxd5aCyxhLrtbTOT/W7zTpXJRx",
	"wi7X4/Fpmqdfbtit4matMk78jIVi56bKJQP1AsGMsKuZ2FC/1vSvzwr3v/z+Fsp5hNJkVsvzbAiRGq/I",
	"tiAswdE16tuGx0s4g2P5GHryIfRU+9DfD5yb93C7rTVmLMoV8pbncfP/dEg9nhI/XM+pkqmZdVo3cXV5",
	"yYEjOJEHpnP14AQG8Cccq+YqD5xlFsbkWrgVBiQpK7eFxv/fIowbjbPTM9OzyiBNSYLTELXQ3PTM9Iye",
	"2WJDH9NTrMUbEpSUcl1cKpW1vyobkML2ej7tmeGECzTY+WCEcMicxvIj5wRjJHz2PHVDOU8JlUR5sqwS",
	"KgnuZFklpLMwi2PMdlRiPJMP5L4KktyvJYciGU4BnCmOFU0T0arSUsHe8yvUdnIMChJ8eaEoLDSKxkyT",
	"aLwfwnCYMx81yi+E7W5+xewowzltqMN6Y3gPrd5eV+yuliJecX/trI6hMtckR+dMjl5K3h06cg8G8vG0",
	"+jyW+/JAPmoCk+fjKFrD/mYTvBYL2f8WbvZsao7YKIGzgvQ5EUsVXmSvmcblar85NSNY3JCEsTFau3jD",
	"c3VqB3pwqji0vC8fwFuTXPLJhdEuQKsgZaAbpXbWNmfeTJaHgpfT5cbpW6NON9+k081fPDdzRqMrp8pl",
	"VlZVgVRS9yUM4A0cldetM5XHcl8+hGPFGyr5WiI9hry3W3kd60zK4GEMFnY0M7tYjVff4Gp1fvkVUJ6/",
	"Uf4LGtD3aSr6oi4fyB8MW7PExsyrpWvnxUgnAtsq0B1172vq48gx6yNMs+V5kVrboFx4iuEpqHP9NQo7",
	"YWK4DnRtfdFVLeHIvqd8b9XNsePWDP4Kp3BY3Mrl/XJDprlefcNz6MKJ/EXu69t5LlzcCGwbXsBAa1fO",
	"/6Sd6xUvJT19+T+EAfQrL8OMKp5sNf6Hjt2pfHJuI3RNEKEPJ9CVe3JvFBL9XpEbGrniWi8TPTVvoO/I",
	"x4Vd+ciBV9peF16XqmLMNsk5ag7lAbyRTx25ZxJuFAv9UFRDw4He0CgM4K+KUfWzNMxIO+TCDtaLkex+",
	"qgGrxroawEot1hU9g75yDw7lk4lKMOcKhNXO3wEAAP//GjTVIHEYAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
