//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Assets struct {
	ID          uuid.UUID `sql:"primary_key"`
	Amount      int32
	Quantity    int32
	PortfolioID uuid.UUID
	MarketID    uuid.UUID
	NotationAt  time.Time
	CreatedAt   time.Time
	UpdatedAt   *time.Time
}
