//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Sessions struct {
	Token     string
	ExpiresAt time.Time
	UserID    uuid.UUID
	Strategy  string
	IP        string
	UserAgent string
	Origin    string
	CreatedAt time.Time
	UpdatedAt *time.Time
}
