//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Users struct {
	ID               uuid.UUID `sql:"primary_key"`
	Name             string
	Email            string
	Password         string
	Role             string
	Avatar           *string
	TokenJoinValue   *uuid.UUID
	TokenJoinExpires *time.Time
	CreatedAt        time.Time
	UpdatedAt        *time.Time
}
